### PR TITLE
Refactor packages

### PR DESCRIPTION
**Pull request by amitav13**

### CODE REVIEW

**Comment by holysheep** [comment]
nice, but is it good title for app "newsapp"?

**Comment by amitav13** [comment]
That's true...I was conflicted on what our organization name should be. Packages are generally named "com.organization.appname". Any suggestions for an organization name?

**Comment by holysheep** [comment]
may be something connected with /r/androiddev

**Comment by amitav13** [comment]
Closing it for now since the changes were just refactors. Can reopen this once we have a name set.

**Pull request closed without merging**
